# Generated by Django 2.1.7 on 2019-04-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ope_date', models.CharField(max_length=10)),
                ('ope_time', models.CharField(max_length=8)),
                ('ope_state', models.CharField(max_length=1)),
                ('ope_machine', models.CharField(max_length=10)),
            ],
        ),
    ]
